name: [DOCKER] Build and Push Image

on:
  push:
    tags: v*
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Build and push Docker images"
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: lukasmoeller/bulletjournal
        tags: lts
        tag_with_ref: true
        path: .
        dockerfile: Dockerfile
        always_pull: true
        labels: name=${{secrets.GITHUB_REPOSITORY}},vcs-url=https://github.com/${{secrets.GITHUB_REPOSITORY}},url=https://getmoeller.com,vendor=Lukas Möller,vcs-ref=${{secrets.GITHUB_SHA}},version=${{ secrets.GITHUB_REF }},description="Docker Image for a very simple BulletJournal"
        add_git_labels: true
        push: true
